### ISSUE TITLE
exec user process caused "exec format error"

### ISSUE THREAD

**Issue by fredkelly** [ilcardella/TradingBot#251]
Hi there,

Thanks for creating such an awesome tool. I've got a bit of a newbie question - I'm trying to run the latest docker image and getting this error on starting:
`standard_init_linux.go:211: exec user process caused "exec format error"`

From reading, it looks as though this comes from missing a shebang, but I'm not sure this is right in this case? I wondered if you can offer some troubleshooting recommendations?

I have created copies of `.credentials` and `config.json` on my local device an mapped them to docker volumes as described in the README.

**Comment by ilcardella** [comment]
Hi, thanks for the feedback! Happy to help with your issue, could tell me more details of your system (Windows/Linux, what architecture, etc) and the steps to reproduce the problem?

**Comment by dFurman** [comment]
Hi @fredkelly,
I had this problem before, not with this particular docker image.
But sometimes it means that the architecture of **your** cpu is **different** from the architecture of the **cpu the docker image was built on**.

one solution to this problem is take the Dockerfile and build the image yourself on your machine.
That way the image will be built with the cpu architecture you are running.

**Comment by ilcardella** [comment]
Hi, I'm not sure if you still have that problem but I have added support for `arm64`, you should be able to pull the Docker image with the tag `latest-arm64` which should work on that architecture. 
Otherwise let us know what platform you were trying the Docker image on.
Unfortunately I do not have any device to test it with, I might try with qemu to run on my amd64 laptop but it would be great if you could confirm that it solves your issue.
For reference the Docker image is [here](https://hub.docker.com/layers/ilcardella/tradingbot/latest-arm64/images/sha256-2f0b0aeaa39838861821d27cf7ce4c08f84f075bd11b7328db6ede736d478e07?context=repo)
